### ISSUE TITLE
fail to open .env

### ISSUE THREAD

**Issue by otbe** [janders223/serverless-offline-ssm#10]
Hi there,

I try to setup ssm/offline-ssm in my current side project, but I get into trouble really quick.
I get `fail to open .env` and searched for similar issues. There is #3, but I think there is a little bit more to say. Thats the reason for opening a new issue. :)

I use `serverless-webpack` and the current working dir in which `serverless-offline-ssm` operates seems to be wrong. I added a console log of `process.cwd()` [here](https://github.com/janders223/serverless-offline-ssm/blob/master/src/start.js#L29) and the output in my current project is `/Users/foo/my-project/packages/service/.webpack/service`, but the real root (and thats the place where my `.env` file is) is `/Users/foo/my-project/packages/service`.

Any ideas what I can do to get it working?

Thank you :)

**Comment by janders223** [comment]
@otbe Thanks for alerting me to this issue. I haven't used or tested the plugin with `serverless-webpack` however, in my experience plugin order as they are listed in `serverless.yml` usually matters.

It sounds like `serverless-offline-ssm` _may_ be loading after `serverless-webpack` causing the issue.

If it's not already, try changing the order of the two plugins in your `serverless.yml` so that it is.

```yaml
plugins:
    - serverless-offline-ssm
    - serverless-webpack
```

Please let me know if this resolves your issue and I will update the README to specify that this plugin must be loaded first.

**Comment by otbe** [comment]
Yeah you're right. Changing the order of the plugins fixed my issue.
Thank you!

**Comment by janders223** [comment]
Thanks for letting me know @otbe. I will update the README to reflect that.
